class_name ContentGenerationMigrationError
extends RefCounted

const PORT_UNCONFIGURED: StringName = &"CONTENT_GENERATION_MIGRATION_PORT_UNCONFIGURED"
const SOURCE_MISMATCH: StringName = &"CONTENT_GENERATION_MIGRATION_SOURCE_MISMATCH"
const PACK_INVALID: StringName = &"CONTENT_GENERATION_MIGRATION_PACK_INVALID"
const PACK_NOT_ALLOWLISTED: StringName = &"CONTENT_GENERATION_MIGRATION_PACK_NOT_ALLOWLISTED"
const TARGET_MISMATCH: StringName = &"CONTENT_GENERATION_MIGRATION_TARGET_MISMATCH"
const PACK_MISSING: StringName = &"CONTENT_GENERATION_MIGRATION_PACK_MISSING"
const PACK_AMBIGUOUS: StringName = &"CONTENT_GENERATION_MIGRATION_PACK_AMBIGUOUS"
const SOURCE_GENERATION_MISSING: StringName = &"CONTENT_GENERATION_MIGRATION_SOURCE_GENERATION_MISSING"
const SOURCE_CATALOG_INVALID: StringName = &"CONTENT_GENERATION_MIGRATION_SOURCE_CATALOG_INVALID"
const MAPPING_INVALID: StringName = &"CONTENT_GENERATION_MIGRATION_MAPPING_INVALID"
const CONFIG_INVALID: StringName = &"CONTENT_GENERATION_MIGRATION_CONFIG_INVALID"
const SELECTION_INCOMPATIBLE: StringName = &"CONTENT_GENERATION_MIGRATION_SELECTION_INCOMPATIBLE"
const PUBLISH_FAILED: StringName = &"CONTENT_GENERATION_MIGRATION_PUBLISH_FAILED"

var code: StringName
var field_path: StringName

func _init(p_code: StringName, p_field_path: StringName) -> void:
	code = p_code
	field_path = p_field_path

func deep_clone() -> ContentGenerationMigrationError:
	return ContentGenerationMigrationError.new(code, field_path)
